name: goperformance
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py39h2bbff1b_1
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - bottleneck=1.3.2=py39h7cc1a96_1
  - brotli=1.0.9=ha925a31_2
  - brotlipy=0.7.0=py39hb82d6ee_1001
  - ca-certificates=2022.5.18.1=h5b45459_0
  - certifi=2022.5.18.1=py39hcbf5309_0
  - cffi=1.14.6=py39h0878f49_1
  - charset-normalizer=2.0.12=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py39hd8d06c1_0
  - cycler=0.10.0=py39haa95532_0
  - daal4py=2021.3.0=py39h757b272_0
  - dal=2021.3.0=haa95532_564
  - dataclasses-json=0.5.7=pyhd8ed1ab_0
  - dateparser=1.0.0=pyhd3eb1b0_0
  - debugpy=1.5.1=py39hd77b12b_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dnspython=2.2.1=pyhd8ed1ab_0
  - entrypoints=0.3=py39haa95532_0
  - fonttools=4.27.1=py39hb82d6ee_0
  - freetype=2.10.4=hd328e21_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py39hcbf5309_0
  - intel-openmp=2021.3.0=haa95532_3372
  - ipykernel=6.4.1=py39haa95532_1
  - ipython=7.29.0=py39hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.0=py39haa95532_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - joblib=0.17.0=py_0
  - jpeg=9d=h2bbff1b_0
  - jsons=1.6.1=pyhd8ed1ab_0
  - jsonschema=3.0.2=py39haa95532_0
  - jupyter=1.0.0=py39haa95532_7
  - jupyter_client=7.1.0=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py39haa95532_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - kiwisolver=1.3.1=py39hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libprotobuf=3.16.0=h7755175_0
  - libtiff=4.2.0=hd0e1b90_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mako=1.1.3=py_0
  - markupsafe=2.0.1=py39h2bbff1b_0
  - marshmallow=3.16.0=pyhd8ed1ab_0
  - marshmallow-enum=1.5.1=pyh9f0ad1d_3
  - matplotlib=3.4.2=py39haa95532_0
  - matplotlib-base=3.4.2=py39h49ac443_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py39h2bbff1b_1000
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py39hcbf5309_5
  - mysql-common=8.0.25=h57928b3_0
  - mysql-connector-python=8.0.25=py39h2d44264_0
  - mysql-libs=8.0.25=hb8c0690_0
  - nbconvert=5.5.0=py_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.6=py39haa95532_0
  - numexpr=2.7.3=py39hb80d3ca_1
  - numpy=1.20.3=py39ha4e8547_0
  - numpy-base=1.20.3=py39hc2deb75_0
  - olefile=0.46=pyhd3eb1b0_0
  - openssl=1.1.1o=h8ffe710_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.3.1=py39h6214cd6_0
  - pandoc=2.12=haa95532_0
  - pandocfilters=1.4.3=py39haa95532_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py39h4fa10fc_0
  - pip=21.2.4=py38haa95532_0
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - protobuf=3.16.0=py39h415ef7b_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyee=8.1.0=pyh9f0ad1d_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyopenssl=21.0.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyppeteer=0.2.6=pyhd8ed1ab_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyrsistent=0.18.0=py39h196d8e1_0
  - pysocks=1.7.1=py39hcbf5309_3
  - python=3.9.7=h6244533_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd3eb1b0_0
  - pywin32=302=py39h827c3e9_1
  - pywinpty=0.5.7=py39haa95532_0
  - pyyaml=5.4.1=py39h2bbff1b_1
  - pyzmq=22.3.0=py39hd77b12b_2
  - qt=5.9.7=vc14h73c81de_0
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - regex=2021.8.3=py39h2bbff1b_0
  - requests=2.27.1=pyhd8ed1ab_0
  - scikit-learn=0.24.2=py39hf11a4ad_1
  - scikit-learn-intelex=2021.3.0=py39haa95532_0
  - scipy=1.7.1=py39hbe87c03_2
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - stringcase=1.2.0=py_0
  - tbb=2021.3.0=h59b6b97_0
  - terminado=0.9.4=py39haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.11=h2bbff1b_0
  - tornado=6.1=py39h2bbff1b_0
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=4.2.0=pyha770c72_1
  - typing_inspect=0.7.1=pyh6c4a22f_0
  - typish=1.9.3=pyhd8ed1ab_0
  - tzdata=2021a=h5d7bf9c_0
  - tzlocal=2.1=py39haa95532_0
  - urllib3=1.26.7=pyhd8ed1ab_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py_1
  - websockets=9.1=py39hb82d6ee_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - widgetsnbextension=3.5.1=py39haa95532_0
  - win_inet_pton=1.1.0=py39hcbf5309_2
  - wincertstore=0.2=py39h2bbff1b_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zipp=3.6.0=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - cssselect2==0.4.1
    - imageio==2.9.0
    - tinycss2==1.1.1
prefix: C:\Users\josep\miniconda3\envs\goperformance
